const EVOLUTION_METHOD = [
  'level-up | level=47',
  'level-up | move=twin-beam',
  'level-up | high-friendship',
  'level-up | level=32',
  'take-at-least-49-damage-without-faint-without-cure | location=dusty-bowl',
  'level-up | level=21',
  'trade | held_item=protector',
  'level-up | level=44',
  'level-up | level=39',
  'trade',
  'trade | held_item=deep-sea-scale',
  'level-up | level=15',
  'level-up | level=16',
  'level-up | level=7',
  'use-item | item=scroll-of-darkness',
  'shed',
  'trade | held_item=whipped-dream',
  'level-up | remoraid-in-party',
  'agile-style-move',
  'level-up | move=hyper-drill',
  'trade | trade_species=shelmet',
  'use-item | item=cracked-pot',
  'use-item | item=sweet-apple',
  'level-up | level=20 | gender=2',
  'use-item | item=dawn-stone | gender=2',
  'level-up | move=double-hit',
  'level-up | level=33',
  'use-item | item=metal-alloy',
  'level-up | level=25 | gender=2',
  'level-up | level=59',
  'trade | held_item=electirizer',
  'level-up | level=64',
  'level-up | level=25 | time=dusk',
  'level-up | time=day | high-friendship',
  'level-up | level=35 | time=night',
  'level-up | level=36 | location=hisui',
  'trade | held_item=up-grade',
  'use-item | item=sun-stone',
  'trade | held_item=prism-scale | or | level-up-with-max-beauty',
  'level-up | level=33 | gender=1',
  'use-item | item=peat-block | time=full-moon',
  'use-item | item=moon-stone',
  'three-defeated-bisharp',
  'use-item | item=galarica-cluff',
  'three-critical-hits',
  'level-up | held_item=oval-stone | time=day',
  'level-up | level=18',
  'level-up | level=54 | location=hisui',
  'level-up | level=50 | needs_overworld_rain',
  'level-up | receive-294-recoil-damage-in-battle',
  'use-item | item=dusk-stone',
  'level-up | held_item=razor-claw | time=day',
  'level-up | level=24',
  'use-item | item=fire-stone',
  'level-up | level=28 | time=night | location=alola',
  'level-up | level=30 | natures=low-key',
  'trade | held_item=dragon-scale',
  'level-up | level=52',
  'use-item | item=black-augurite',
  'level-up | level=18 | gender=1',
  'level-up | level=42',
  'use-item | item=leaf-stone | location=alola',
  'level-up | level=36',
  'trade | trade_species=karrablast',
  'level-up | level=20 | time=day',
  'barb-barrage-20-times-in-strong-style-move',
  'level-up | level=20 | gender=1 | location=caves',
  'trade | held_item=reaper-cloth',
  'level-up | level=38',
  'level-up | level=49',
  'level-up | move=ancient-power',
  'level-up | level=39 | time=night',
  'level-up | move=taunt',
  'level-up | held_item=razor-fang | time=night',
  'level-up | level=37',
  'level-up | level=26',
  'level-up | level=12',
  'level=25 | rare',
  'level-up | level=25 | time=night',
  'level-up | level=17',
  'level-up | level=20',
  'level-up | level=37 | location=hisui',
  'level-up | item=ice-stone | or | location=mount-lanakila',
  'use-item | item=ice-stone',
  'level-up | item=thunder-stone | or | location=magnetic_field',
  'trade | held_item=dubious-disc',
  'level-up | level=25 | time=day',
  'level-up | level=23',
  'level=25',
  'level-up | level=9',
  'level-up | level=31',
  'level-up | item=leaf-stone | or | location=moss-rock',
  'level-up | move=mimic | location=galar',
  'use-item | item=leaf-stone',
  'level-up | level=28',
  'trade | held_item=magmarizer',
  'use-item | item=sun-stone | location=hisui',
  'level-up | level=43',
  'use-item | item=syrupy-apple',
  'use-item | item=thunder-stone | location=alola',
  'level-up | level=25',
  'spin',
  'level-up | level=41',
  'level-up | level=27',
  'level-up | move=stomp',
  'use-item | item=thunder-stone',
  'level-up | level=25 | gender=1',
  'use-move',
  'level-up | level=35',
  'level-up | level=20 | time=night',
  'walk-1000-steps-in-lets-go-mode',
  'level-up | level=20 | gender=1 | location=grass',
  'level-up | move_type=fairy | high-friendship',
  'use-item | item=auspicious-armor',
  'use-item | item=dawn-stone | gender=1',
  'use-item | item=galarica-wreath',
  'use-item | item=unremarkable-teacup',
  'level-up | level=35 | location=galar',
  'level-up | level=14',
  'level-up | level=30 | natures=amped',
  'level-up | level=10',
  'level-up | move=mimic',
  'use-item | item=shiny-stone',
  'trade | held_item=sachet',
  'level-up | level=40',
  'level-up | time=night | high-friendship',
  'level-up | level=53',
  'level-up | level=21 | gender=1',
  'level-up | move=rollout',
  'level-up | item=ice-stone | or | location=ice-rock',
  'level-up | level=48',
  'level-up | level=54',
  'level-up | level=20 | gender=1 | location=buildings',
  'use-item | item=malicious-armor',
  'level-up | level=34 | time=day',
  'level-up | level=55',
  'level-up | level=60',
  'use-item | item=tart-apple',
  'level-up | level=40 | location=hisui',
  'level-up | level=30 | time=night',
  'level-up | level=39 | time=day',
  'level-up | level=50',
  'level-up | level=19',
  'gimmighoul-coins',
  'use-item | item=water-stone',
  'level-up | level=45',
  'level-up | level=34',
  'level-up | item=thunder-stone | or | location=magnetic-field',
  'level-up | move=dragon-cheer',
  'trade | held_item=kings-rock',
  'level-up | move=dragon-pulse',
  'trade | held_item=metal-coat',
  'level-up | level=22',
  'level-up | level=30 | turn_upside_down',
  'level-up | level=30',
  'use-item | item=scroll-of-waters',
  'level-up | level=18 | gender=2',
  'level-up | held_item=razor-claw | time=night',
  'trade | held_item=deep-sea-tooth',
  'level-up | level=29',
];

function getEvoMethod(evolutions: string[]) {
}